project:
  type: website

website:
  title: "Isaiah Jeter's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: prime.qmd
        text: Amazon Prime Air
      - href: ahi.qmd
        text: Amidon Heavy Industries
      - href: apple.qmd
        text: Apple
      - href: aah.qmd
        text: Advanced Alloy Holdings
      - href: dhd.qmd
        text: Digital Hardware Design

          

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

metadata-files:
  - dhdProjects/_metadata.yml


