project:
  type: website

website:
  title: "Isaiah Jeter's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: dhd.qmd
        text: Digital Hardware Design
      - href: control.qmd
        text: Control Systems
      - href: eBoat.qmd
        text: Electric Boat
          

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

metadata-files:
  - dhdProjects/_metadata.yml


