project:
  type: website

website:
  title: "Isaiah Jeter's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Amidon Heavy Industries
        menu:
          - text: AHI Homepage
            href: ahi.qmd
          - text: "---"
          - text: "Communication Network"       # You choose the label
            href: ahiProjects/comNetwork.qmd # Point to specific file
          - text: "Winch Driver and Remote Controller"
            href: ahiProjects/winch.qmd
          - text: "Control System for AUV"
            href: ahiProjects/finControls.qmd
          - text: "Subsea Simulation for AUV"
            href: ahiProjects/simulation.qmd
      - href: prime.qmd
        text: Amazon Prime Air
      - href: apple.qmd
        text: Apple
      - href: aah.qmd
        text: LASPA Alloy
      - href: dhd.qmd
        text: Digital Hardware Design
      # - href: qbsk.qmd
      #   text: OQPSK Demo


          

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

metadata-files:
  - dhdProjects/_metadata.yml


